config/routes.rb
FreeMarket::Application.routes.draw do
  resources :users
  resources :items
  get "tags/:tag", to: "items#index", as: :tag
  root to: "items#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :read, :all
    can [:update, :destroy], User, id: user.id
    can :create,  Item
    can [:update, :destroy], Item, user_id: user.id

    if user.role == "moderator"
      can :manage, [User, Item]
      cannot :update, :role
    end

    if user.role == "admin"
      can :manage, :all
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_attached_file :item_image, styles: { medium: "300x300>", thumb: "100x100>" },
                                 default_url: "/images/:style/missing.png"

  validates :name, presence: true, length: { maximum: 75 }
  validates :description, length: { maximum: 2000 }
  validates :user_id, presence: true
  validates :address, presence: true

  validates_attachment :item_image,
                        content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
                        matches: [/jpe?g\Z/, /gif\Z/, /png\Z/],
                        size: { less_than: 10.megabytes }



  def self.search(search)
    if search
      where('name ILIKE ?', "%#{search}%").load
    else
      where(@item = true).load
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :items, -> { order 'created_at DESC' }, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, name_convention: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  ROLES = %w[admin moderator user]

  def self.search(search)
    if search
      where('name ILIKE ? OR email ILIKE?', "%#{search}%", "%#{search}%").load
    else
      where(@user = true).load
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :require_login, except: [:index, :show]

  load_resource
  authorize_resource except: [:index, :show]

  def index
    if params[:tag]
      @items = Item.order("created_at DESC").tagged_with(params[:tag]).search(params[:term])
    else
      @items = Item.order("created_at DESC").search(params[:term])
    end
    @paginated_items = Kaminari.paginate_array(@items).page(params[:page]).per(15)
    respond_to do |format|
      format.html
      format.json{ render json: @items }
    end
  end

  def show
  end

  def new
  end

  def create
    @item.user_id = current_user.id
    if @item.save
      redirect_to @item
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @item.update_attributes(item_params)
      redirect_to @item
    else
      render "edit"
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url
  end

  def item_params
    params.require(:item).permit(:name, :description, :user_id, :item_image,
                                 :tag_list, :address, :latitude, :longitude)
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  before_filter :cancan_strong_parameters

  load_resource
  authorize_resource only: [:edit, :update, :destroy]

  def index
    @users = User.order("name").search(params[:term])
    @paginated_users = Kaminari.paginate_array(@users).page(params[:page])
  end

  def show
  end

  def new
  end

  def create
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def user_params
    if current_user && current_user.role == "admin"
      params.require(:user).permit(:name, :email, :password, :role)
    else
      params.require(:user).permit(:name, :email, :password)
    end
  end

  def user_from_params
    user_params = params[:user] || Hash.new
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    name = user_params.delete(:name)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.name = name
    end
  end

  def cancan_strong_parameters
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<div class="form">
  <%= simple_form_for @item, html: { multipart: true } do |f| %>
    <div class='text-field'>
      <%= f.input :name, type: "name" %>
    </div>

    <div class='text-field'>
      <%= f.input :address, type: "address" %>
    </div>

    <div class='text-field'>
      <%= f.input :tag_list, type: "tags", label: "Tags", hint: "separated by commas" %>
    </div>

    <div class='text-field'>
      <%= f.input :description, type: "description" %>
    </div>

    <div class='text-field'>
      <%= f.input :latitude, as: :hidden, type: "latitude" %>
    </div>

    <div class='text-field'>
      <%= f.input :longitude, as: :hidden, type: "longitude" %>
    </div>

    <div id='attachment-preview'>
      <% if @item.item_image? %>
        <%= image_tag @item.item_image.url(:thumb) %>
      <% end %>
    </div>

    <div class='attachment-field'>
      <%= f.input :item_image, label: "Image" %>
    </div>

    <div class='submit-field'>
      <%= f.button :submit %>
    </div>

  <% end %>
</div>

app/views/items/edit.html.erb
<h1>edit item</h1>

<%= render "items/form" %>

app/views/items/index.html.erb
<h1>item index</h1>

<%= render partial: 'shared/page_with_search',
           locals: {search_path: items_path, search_placeholder: "item search.."} %>

<% if @items.empty? %>
  no results..
<% else %>
  <div id="map"></div>

  <div id="tag_cloud">
    <b>Tag cloud:</b>
    <br>
    <% tag_cloud Item.tag_counts.sort { |x, y| x.name <=> y.name }, %w[s m l] do |tag, css_class| %>
      <div><%= link_to tag.name, tag_path(tag.name), class: css_class %></div>
    <% end %>
  </div>
  <br>
  <table class="index">
    <tr>
      <th>items:</th>
    </tr>
    <% @paginated_items.each do |item| %>
      <tr>
        <td><%= image_tag item.item_image.url(:thumb) %></td>
        <td><%= link_to item.name, item %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= paginate @paginated_items %>

app/views/items/new.html.erb
<h1>new item</h1>

<%= render "items/form" %>

app/views/items/show.html.erb
<h1>Item info</h1>

<div id="static_map">
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=15&markers=#{@item.latitude}%2C#{@item.longitude}" %>
</div>

<div>
  <div class="update-destroy">
    <% if can? :update, @item %>
      <%= link_to "edit", edit_item_path %>
    <% end %>
    <% if can? :destroy, @item %>
      <%= link_to "delete", @item, method: :delete, data: { confirm: "are you sure?" } %>
    <% end %>
  </div>
  <table>
    <tr>
      <td><%= link_to image_tag(@item.item_image.url(:medium)), @item.item_image.url %></td>
    </tr>
    <tr>
      <td><b>name:</b></td>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <td><b>added by:</b></td>
      <td><%= link_to @item.user.name, @item.user %>, <%= @item.created_at %></td>
    </tr>
    <tr>
      <td><b>address:</b></td>
      <td><%= @item.address %></td>
    </tr>
    <tr>
      <td><b>tags:</b></td>
      <td><%= raw @item.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
    </tr>
    <tr>
      <td><b>description:</b></td>
      <td><%= @item.description %></td>
    </tr>
  </table>

  <table class="index" id="splitter">
    <% if @item.nearbys(100).any? %>
      <tr>
        <th>nearby items:</th>
      </tr>
      <% @item.nearbys(100).each do |item| %>
        <tr>
          <td><%= image_tag item.item_image.url(:thumb) %></td>
          <td><%= link_to item.name, item %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td><%= "#{@item.name} has not any nearby items" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FreeMarket</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <ul>
      <li><%= link_to "Add Item", new_item_path %></li>
      <li><%= link_to "Items", items_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <li>
        <% if signed_in? %>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to "Sign out", sign_out_path, method: :delete %></li>
          <li id="signed_as"><%= current_user.email %></li>
        <% else %>
          <%= link_to "Sign in", sign_in_path %>
        <% end %>
      </li>
    </ul>
  </header>

  <div>
    <%= yield %>
  </div>

  <footer>
    <div class="footer-left">
      <span>contact us:</span>
      <span>freemarket@example.com</span>
    </div>
    <div class="footer-right">
      <span>copyleft (ɔ)</span>
      <span>free to use and modify</span>
    </div>
  </footer>
</body>
</html>

app/views/shared/_page_with_search.html.erb
<div id="search">
  <%= simple_form_for search_path, method: :get, html: { class: :search } do %>
    <%= text_field_tag :term, params[:term], placeholder: search_placeholder %>
    <%= submit_tag "search", name: nil %>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <div class='text-field'>
    <%= f.input :name, type: "name" %>
  </div>

  <div class='text-field'>
    <%= f.input :email, type: "email" %>
  </div>

  <div class='password-field'>
    <%= f.input :password, type: "password" %>
  </div>

  <% if current_user && current_user.role == "admin" %>
    <div>
      <%= f.collection_select :role, User::ROLES, :to_s, :humanize %>
    </div>
  <% end %>

  <div class='submit-field'>
    <%= f.button :submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render "/users/form" %>

app/views/users/index.html.erb
<h1>User index</h1>

<%= render partial: 'shared/page_with_search',
           locals: {search_path: users_path, search_placeholder: "user search.."} %>

<% if @users.empty? %>
  no results..
<% else %>
  <table class="index">
    <tr>
      <th>name</th>
      <th>email</th>
    </tr>
    <% @paginated_users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<%= paginate @paginated_users %>

app/views/users/new.html.erb
<div id='clearance' class='sign-up'>
  <h2><%= t('.title') %></h2>

  <%= render "/users/form" %>

  <div class='other-links'>
    <%= link_to t('.sign_in'), sign_in_path %>
  </div>

</div>

app/views/users/show.html.erb
<h1>User info</h1>

<div>
  <div class="update-destroy">
    <% if can? :update, @user %>
      <%= link_to "edit", edit_user_path %>
    <%end%>
    <% if can? :destroy, @user %>
      <%= link_to "delete", @user, method: :delete, data: { confirm: "are you sure?" } %>
    <% end %>
  </div>
  <table>
    <tr>
      <td><b>name:</b></td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <td><b>email:</b></td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td><b>role:</b></td>
      <td><%= @user.role %></td>
    </tr>
  </table>
</div>

<table class="index" id="splitter">
  <% if @user.items.any? %>
    <tr>
      <th>items added:</th>
    </tr>
    <% @user.items.each do |item| %>
      <tr>
        <td><%= image_tag item.item_image.url(:thumb) %></td>
        <td><%= link_to item.name, item %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td><%= "#{@user.name} has not added any items yet" %></td>
    </tr>
  <% end %>
</table>